// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/localDiscoveryProtos.proto

package it.anyplace.sync.discovery.protocol.ld.protos;

public final class LocalDiscoveryProtos {
  private LocalDiscoveryProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AnnounceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes id = 1;
    /**
     * <code>optional bytes id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional bytes id = 1;</code>
     */
    com.google.protobuf.ByteString getId();

    // repeated string addresses = 2;
    /**
     * <code>repeated string addresses = 2;</code>
     */
    java.util.List<java.lang.String>
    getAddressesList();
    /**
     * <code>repeated string addresses = 2;</code>
     */
    int getAddressesCount();
    /**
     * <code>repeated string addresses = 2;</code>
     */
    java.lang.String getAddresses(int index);
    /**
     * <code>repeated string addresses = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddressesBytes(int index);

    // optional int64 instance_id = 3;
    /**
     * <code>optional int64 instance_id = 3;</code>
     */
    boolean hasInstanceId();
    /**
     * <code>optional int64 instance_id = 3;</code>
     */
    long getInstanceId();
  }
  /**
   * Protobuf type {@code it.anyplace.sync.core.protocol.ld.protos.Announce}
   */
  public static final class Announce extends
      com.google.protobuf.GeneratedMessage
      implements AnnounceOrBuilder {
    // Use Announce.newBuilder() to construct.
    private Announce(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Announce(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Announce defaultInstance;
    public static Announce getDefaultInstance() {
      return defaultInstance;
    }

    public Announce getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Announce(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                addresses_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              addresses_.add(input.readBytes());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              instanceId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          addresses_ = new com.google.protobuf.UnmodifiableLazyStringList(addresses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.internal_static_it_anyplace_sync_core_protocol_ld_protos_Announce_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.internal_static_it_anyplace_sync_core_protocol_ld_protos_Announce_fieldAccessorTable
          .ensureFieldAccessorsInitialized(it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce.class, it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce.Builder.class);
    }

    public static com.google.protobuf.Parser<Announce> PARSER =
        new com.google.protobuf.AbstractParser<Announce>() {
      public Announce parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Announce(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Announce> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>optional bytes id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    // repeated string addresses = 2;
    public static final int ADDRESSES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList addresses_;
    /**
     * <code>repeated string addresses = 2;</code>
     */
    public java.util.List<java.lang.String>
        getAddressesList() {
      return addresses_;
    }
    /**
     * <code>repeated string addresses = 2;</code>
     */
    public int getAddressesCount() {
      return addresses_.size();
    }
    /**
     * <code>repeated string addresses = 2;</code>
     */
    public java.lang.String getAddresses(int index) {
      return addresses_.get(index);
    }
    /**
     * <code>repeated string addresses = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressesBytes(int index) {
      return addresses_.getByteString(index);
    }

    // optional int64 instance_id = 3;
    public static final int INSTANCE_ID_FIELD_NUMBER = 3;
    private long instanceId_;
    /**
     * <code>optional int64 instance_id = 3;</code>
     */
    public boolean hasInstanceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 instance_id = 3;</code>
     */
    public long getInstanceId() {
      return instanceId_;
    }

    private void initFields() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      instanceId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, id_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        output.writeBytes(2, addresses_.getByteString(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, instanceId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addresses_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(addresses_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getAddressesList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, instanceId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.anyplace.sync.core.protocol.ld.protos.Announce}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.AnnounceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.internal_static_it_anyplace_sync_core_protocol_ld_protos_Announce_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.internal_static_it_anyplace_sync_core_protocol_ld_protos_Announce_fieldAccessorTable
            .ensureFieldAccessorsInitialized(it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce.class, it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce.Builder.class);
      }

      // Construct using it.anyplace.sync.core.protocol.ld.protos.LocalDiscoveryProtos.Announce.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        instanceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.internal_static_it_anyplace_sync_core_protocol_ld_protos_Announce_descriptor;
      }

      public it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce getDefaultInstanceForType() {
        return  it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce.getDefaultInstance();
      }

      public it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce build() {
                it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce buildPartial() {
                it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce result = new it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          addresses_ = new com.google.protobuf.UnmodifiableLazyStringList(
              addresses_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.addresses_ = addresses_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.instanceId_ = instanceId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce) {
          return mergeFrom((it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce other) {
        if (other == it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.addresses_.isEmpty()) {
          if (addresses_.isEmpty()) {
            addresses_ = other.addresses_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAddressesIsMutable();
            addresses_.addAll(other.addresses_);
          }
          onChanged();
        }
        if (other.hasInstanceId()) {
          setInstanceId(other.getInstanceId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.anyplace.sync.discovery.protocol.ld.protos.LocalDiscoveryProtos.Announce) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes id = 1;
      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes id = 1;</code>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>optional bytes id = 1;</code>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      // repeated string addresses = 2;
      private com.google.protobuf.LazyStringList addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          addresses_ = new com.google.protobuf.LazyStringArrayList(addresses_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public java.util.List<java.lang.String>
          getAddressesList() {
        return java.util.Collections.unmodifiableList(addresses_);
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public int getAddressesCount() {
        return addresses_.size();
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public java.lang.String getAddresses(int index) {
        return addresses_.get(index);
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressesBytes(int index) {
        return addresses_.getByteString(index);
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public Builder setAddresses(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public Builder addAddresses(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public Builder addAllAddresses(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddressesIsMutable();
        super.addAll(values, addresses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public Builder clearAddresses() {
        addresses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addresses = 2;</code>
       */
      public Builder addAddressesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
        return this;
      }

      // optional int64 instance_id = 3;
      private long instanceId_ ;
      /**
       * <code>optional int64 instance_id = 3;</code>
       */
      public boolean hasInstanceId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 instance_id = 3;</code>
       */
      public long getInstanceId() {
        return instanceId_;
      }
      /**
       * <code>optional int64 instance_id = 3;</code>
       */
      public Builder setInstanceId(long value) {
        bitField0_ |= 0x00000004;
        instanceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 instance_id = 3;</code>
       */
      public Builder clearInstanceId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        instanceId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:it.anyplace.sync.core.protocol.ld.protos.Announce)
    }

    static {
      defaultInstance = new Announce(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:it.anyplace.sync.core.protocol.ld.protos.Announce)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_it_anyplace_sync_core_protocol_ld_protos_Announce_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_it_anyplace_sync_core_protocol_ld_protos_Announce_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/main/resources/localDiscoveryProto" +
      "s.proto\022(it.anyplace.sync.core.protocol." +
      "ld.protos\">\n\010Announce\022\n\n\002id\030\001 \001(\014\022\021\n\tadd" +
      "resses\030\002 \003(\t\022\023\n\013instance_id\030\003 \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_it_anyplace_sync_core_protocol_ld_protos_Announce_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_it_anyplace_sync_core_protocol_ld_protos_Announce_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_it_anyplace_sync_core_protocol_ld_protos_Announce_descriptor,
              new java.lang.String[] { "Id", "Addresses", "InstanceId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
