// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/httpRelayProtos.proto

package it.anyplace.sync.httprelay.protos;

public final class HttpRelayProtos {
  private HttpRelayProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType}
   */
  public enum HttpRelayPeerMessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CONNECT = 0;</code>
     */
    CONNECT(0, 0),
    /**
     * <code>PEER_TO_RELAY = 1;</code>
     */
    PEER_TO_RELAY(1, 1),
    /**
     * <code>WAIT_FOR_DATA = 2;</code>
     */
    WAIT_FOR_DATA(2, 2),
    /**
     * <code>PEER_CLOSING = 3;</code>
     */
    PEER_CLOSING(3, 3),
    ;

    /**
     * <code>CONNECT = 0;</code>
     */
    public static final int CONNECT_VALUE = 0;
    /**
     * <code>PEER_TO_RELAY = 1;</code>
     */
    public static final int PEER_TO_RELAY_VALUE = 1;
    /**
     * <code>WAIT_FOR_DATA = 2;</code>
     */
    public static final int WAIT_FOR_DATA_VALUE = 2;
    /**
     * <code>PEER_CLOSING = 3;</code>
     */
    public static final int PEER_CLOSING_VALUE = 3;


    public final int getNumber() { return value; }

    public static HttpRelayPeerMessageType valueOf(int value) {
      switch (value) {
        case 0: return CONNECT;
        case 1: return PEER_TO_RELAY;
        case 2: return WAIT_FOR_DATA;
        case 3: return PEER_CLOSING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HttpRelayPeerMessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<HttpRelayPeerMessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HttpRelayPeerMessageType>() {
            public HttpRelayPeerMessageType findValueByNumber(int number) {
              return HttpRelayPeerMessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return it.anyplace.sync.httprelay.protos.HttpRelayProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final HttpRelayPeerMessageType[] VALUES = values();

    public static HttpRelayPeerMessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private HttpRelayPeerMessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType)
  }

  /**
   * Protobuf enum {@code it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType}
   */
  public enum HttpRelayServerMessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PEER_CONNECTED = 0;</code>
     */
    PEER_CONNECTED(0, 0),
    /**
     * <code>DATA_ACCEPTED = 1;</code>
     */
    DATA_ACCEPTED(1, 1),
    /**
     * <code>RELAY_TO_PEER = 2;</code>
     */
    RELAY_TO_PEER(2, 2),
    /**
     * <code>SERVER_CLOSING = 3;</code>
     */
    SERVER_CLOSING(3, 3),
    /**
     * <code>ERROR = 4;</code>
     */
    ERROR(4, 4),
    ;

    /**
     * <code>PEER_CONNECTED = 0;</code>
     */
    public static final int PEER_CONNECTED_VALUE = 0;
    /**
     * <code>DATA_ACCEPTED = 1;</code>
     */
    public static final int DATA_ACCEPTED_VALUE = 1;
    /**
     * <code>RELAY_TO_PEER = 2;</code>
     */
    public static final int RELAY_TO_PEER_VALUE = 2;
    /**
     * <code>SERVER_CLOSING = 3;</code>
     */
    public static final int SERVER_CLOSING_VALUE = 3;
    /**
     * <code>ERROR = 4;</code>
     */
    public static final int ERROR_VALUE = 4;


    public final int getNumber() { return value; }

    public static HttpRelayServerMessageType valueOf(int value) {
      switch (value) {
        case 0: return PEER_CONNECTED;
        case 1: return DATA_ACCEPTED;
        case 2: return RELAY_TO_PEER;
        case 3: return SERVER_CLOSING;
        case 4: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HttpRelayServerMessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<HttpRelayServerMessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HttpRelayServerMessageType>() {
            public HttpRelayServerMessageType findValueByNumber(int number) {
              return HttpRelayServerMessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return it.anyplace.sync.httprelay.protos.HttpRelayProtos.getDescriptor().getEnumTypes().get(1);
    }

    private static final HttpRelayServerMessageType[] VALUES = values();

    public static HttpRelayServerMessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private HttpRelayServerMessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType)
  }

  public interface HttpRelayPeerMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType message_type = 1;
    /**
     * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType message_type = 1;</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType message_type = 1;</code>
     */
    it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType getMessageType();

    // optional string session_id = 2;
    /**
     * <code>optional string session_id = 2;</code>
     */
    boolean hasSessionId();
    /**
     * <code>optional string session_id = 2;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>optional string session_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    // optional string device_id = 3;
    /**
     * <code>optional string device_id = 3;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>optional string device_id = 3;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>optional string device_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    // optional int64 sequence = 4;
    /**
     * <code>optional int64 sequence = 4;</code>
     */
    boolean hasSequence();
    /**
     * <code>optional int64 sequence = 4;</code>
     */
    long getSequence();

    // optional bytes data = 5;
    /**
     * <code>optional bytes data = 5;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 5;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code it.anyplace.sync.httprelay.protos.HttpRelayPeerMessage}
   */
  public static final class HttpRelayPeerMessage extends
      com.google.protobuf.GeneratedMessage
      implements HttpRelayPeerMessageOrBuilder {
    // Use HttpRelayPeerMessage.newBuilder() to construct.
    private HttpRelayPeerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HttpRelayPeerMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HttpRelayPeerMessage defaultInstance;
    public static HttpRelayPeerMessage getDefaultInstance() {
      return defaultInstance;
    }

    public HttpRelayPeerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HttpRelayPeerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType value = it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sessionId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              deviceId_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sequence_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.anyplace.sync.httprelay.protos.HttpRelayProtos.internal_static_it_anyplace_sync_httprelay_protos_HttpRelayPeerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.anyplace.sync.httprelay.protos.HttpRelayProtos.internal_static_it_anyplace_sync_httprelay_protos_HttpRelayPeerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage.class, it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<HttpRelayPeerMessage> PARSER =
        new com.google.protobuf.AbstractParser<HttpRelayPeerMessage>() {
      public HttpRelayPeerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HttpRelayPeerMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HttpRelayPeerMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType message_type = 1;
    public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
    private it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType messageType_;
    /**
     * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType message_type = 1;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType message_type = 1;</code>
     */
    public it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType getMessageType() {
      return messageType_;
    }

    // optional string session_id = 2;
    public static final int SESSION_ID_FIELD_NUMBER = 2;
    private java.lang.Object sessionId_;
    /**
     * <code>optional string session_id = 2;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string session_id = 2;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string session_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string device_id = 3;
    public static final int DEVICE_ID_FIELD_NUMBER = 3;
    private java.lang.Object deviceId_;
    /**
     * <code>optional string device_id = 3;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string device_id = 3;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 sequence = 4;
    public static final int SEQUENCE_FIELD_NUMBER = 4;
    private long sequence_;
    /**
     * <code>optional int64 sequence = 4;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 sequence = 4;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    // optional bytes data = 5;
    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 5;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes data = 5;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      messageType_ = it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType.CONNECT;
      sessionId_ = "";
      deviceId_ = "";
      sequence_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, sequence_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, sequence_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.anyplace.sync.httprelay.protos.HttpRelayPeerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.anyplace.sync.httprelay.protos.HttpRelayProtos.internal_static_it_anyplace_sync_httprelay_protos_HttpRelayPeerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.anyplace.sync.httprelay.protos.HttpRelayProtos.internal_static_it_anyplace_sync_httprelay_protos_HttpRelayPeerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage.class, it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage.Builder.class);
      }

      // Construct using it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageType_ = it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType.CONNECT;
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        sequence_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.anyplace.sync.httprelay.protos.HttpRelayProtos.internal_static_it_anyplace_sync_httprelay_protos_HttpRelayPeerMessage_descriptor;
      }

      public it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage getDefaultInstanceForType() {
        return it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage.getDefaultInstance();
      }

      public it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage build() {
        it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage buildPartial() {
        it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage result = new it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sequence_ = sequence_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage) {
          return mergeFrom((it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage other) {
        if (other == it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000002;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000004;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType message_type = 1;
      private it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType messageType_ = it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType.CONNECT;
      /**
       * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType message_type = 1;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType message_type = 1;</code>
       */
      public it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType message_type = 1;</code>
       */
      public Builder setMessageType(it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayPeerMessageType message_type = 1;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayPeerMessageType.CONNECT;
        onChanged();
        return this;
      }

      // optional string session_id = 2;
      private java.lang.Object sessionId_ = "";
      /**
       * <code>optional string session_id = 2;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string session_id = 2;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string session_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string session_id = 2;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string session_id = 2;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string session_id = 2;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessionId_ = value;
        onChanged();
        return this;
      }

      // optional string device_id = 3;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>optional string device_id = 3;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string device_id = 3;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_id = 3;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 3;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 3;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // optional int64 sequence = 4;
      private long sequence_ ;
      /**
       * <code>optional int64 sequence = 4;</code>
       */
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 sequence = 4;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>optional int64 sequence = 4;</code>
       */
      public Builder setSequence(long value) {
        bitField0_ |= 0x00000008;
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sequence = 4;</code>
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sequence_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes data = 5;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 5;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes data = 5;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 5;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 5;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:it.anyplace.sync.httprelay.protos.HttpRelayPeerMessage)
    }

    static {
      defaultInstance = new HttpRelayPeerMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:it.anyplace.sync.httprelay.protos.HttpRelayPeerMessage)
  }

  public interface HttpRelayServerMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType message_type = 1;
    /**
     * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType message_type = 1;</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType message_type = 1;</code>
     */
    it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType getMessageType();

    // optional string session_id = 2;
    /**
     * <code>optional string session_id = 2;</code>
     */
    boolean hasSessionId();
    /**
     * <code>optional string session_id = 2;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>optional string session_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    // optional bool is_server_socket = 3;
    /**
     * <code>optional bool is_server_socket = 3;</code>
     */
    boolean hasIsServerSocket();
    /**
     * <code>optional bool is_server_socket = 3;</code>
     */
    boolean getIsServerSocket();

    // optional int64 sequence = 4;
    /**
     * <code>optional int64 sequence = 4;</code>
     */
    boolean hasSequence();
    /**
     * <code>optional int64 sequence = 4;</code>
     */
    long getSequence();

    // optional bytes data = 5;
    /**
     * <code>optional bytes data = 5;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 5;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code it.anyplace.sync.httprelay.protos.HttpRelayServerMessage}
   */
  public static final class HttpRelayServerMessage extends
      com.google.protobuf.GeneratedMessage
      implements HttpRelayServerMessageOrBuilder {
    // Use HttpRelayServerMessage.newBuilder() to construct.
    private HttpRelayServerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HttpRelayServerMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HttpRelayServerMessage defaultInstance;
    public static HttpRelayServerMessage getDefaultInstance() {
      return defaultInstance;
    }

    public HttpRelayServerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HttpRelayServerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType value = it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sessionId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isServerSocket_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sequence_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.anyplace.sync.httprelay.protos.HttpRelayProtos.internal_static_it_anyplace_sync_httprelay_protos_HttpRelayServerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.anyplace.sync.httprelay.protos.HttpRelayProtos.internal_static_it_anyplace_sync_httprelay_protos_HttpRelayServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage.class, it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<HttpRelayServerMessage> PARSER =
        new com.google.protobuf.AbstractParser<HttpRelayServerMessage>() {
      public HttpRelayServerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HttpRelayServerMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HttpRelayServerMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType message_type = 1;
    public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
    private it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType messageType_;
    /**
     * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType message_type = 1;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType message_type = 1;</code>
     */
    public it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType getMessageType() {
      return messageType_;
    }

    // optional string session_id = 2;
    public static final int SESSION_ID_FIELD_NUMBER = 2;
    private java.lang.Object sessionId_;
    /**
     * <code>optional string session_id = 2;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string session_id = 2;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string session_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool is_server_socket = 3;
    public static final int IS_SERVER_SOCKET_FIELD_NUMBER = 3;
    private boolean isServerSocket_;
    /**
     * <code>optional bool is_server_socket = 3;</code>
     */
    public boolean hasIsServerSocket() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool is_server_socket = 3;</code>
     */
    public boolean getIsServerSocket() {
      return isServerSocket_;
    }

    // optional int64 sequence = 4;
    public static final int SEQUENCE_FIELD_NUMBER = 4;
    private long sequence_;
    /**
     * <code>optional int64 sequence = 4;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 sequence = 4;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    // optional bytes data = 5;
    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 5;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes data = 5;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      messageType_ = it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType.PEER_CONNECTED;
      sessionId_ = "";
      isServerSocket_ = false;
      sequence_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isServerSocket_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, sequence_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isServerSocket_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, sequence_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.anyplace.sync.httprelay.protos.HttpRelayServerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.anyplace.sync.httprelay.protos.HttpRelayProtos.internal_static_it_anyplace_sync_httprelay_protos_HttpRelayServerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.anyplace.sync.httprelay.protos.HttpRelayProtos.internal_static_it_anyplace_sync_httprelay_protos_HttpRelayServerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage.class, it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage.Builder.class);
      }

      // Construct using it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageType_ = it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType.PEER_CONNECTED;
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        isServerSocket_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        sequence_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.anyplace.sync.httprelay.protos.HttpRelayProtos.internal_static_it_anyplace_sync_httprelay_protos_HttpRelayServerMessage_descriptor;
      }

      public it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage getDefaultInstanceForType() {
        return it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage.getDefaultInstance();
      }

      public it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage build() {
        it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage buildPartial() {
        it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage result = new it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isServerSocket_ = isServerSocket_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sequence_ = sequence_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage) {
          return mergeFrom((it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage other) {
        if (other == it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000002;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasIsServerSocket()) {
          setIsServerSocket(other.getIsServerSocket());
        }
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType message_type = 1;
      private it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType messageType_ = it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType.PEER_CONNECTED;
      /**
       * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType message_type = 1;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType message_type = 1;</code>
       */
      public it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType message_type = 1;</code>
       */
      public Builder setMessageType(it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .it.anyplace.sync.httprelay.protos.HttpRelayServerMessageType message_type = 1;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = it.anyplace.sync.httprelay.protos.HttpRelayProtos.HttpRelayServerMessageType.PEER_CONNECTED;
        onChanged();
        return this;
      }

      // optional string session_id = 2;
      private java.lang.Object sessionId_ = "";
      /**
       * <code>optional string session_id = 2;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string session_id = 2;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string session_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string session_id = 2;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string session_id = 2;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string session_id = 2;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessionId_ = value;
        onChanged();
        return this;
      }

      // optional bool is_server_socket = 3;
      private boolean isServerSocket_ ;
      /**
       * <code>optional bool is_server_socket = 3;</code>
       */
      public boolean hasIsServerSocket() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool is_server_socket = 3;</code>
       */
      public boolean getIsServerSocket() {
        return isServerSocket_;
      }
      /**
       * <code>optional bool is_server_socket = 3;</code>
       */
      public Builder setIsServerSocket(boolean value) {
        bitField0_ |= 0x00000004;
        isServerSocket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_server_socket = 3;</code>
       */
      public Builder clearIsServerSocket() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isServerSocket_ = false;
        onChanged();
        return this;
      }

      // optional int64 sequence = 4;
      private long sequence_ ;
      /**
       * <code>optional int64 sequence = 4;</code>
       */
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 sequence = 4;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>optional int64 sequence = 4;</code>
       */
      public Builder setSequence(long value) {
        bitField0_ |= 0x00000008;
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sequence = 4;</code>
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sequence_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes data = 5;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 5;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes data = 5;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 5;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 5;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:it.anyplace.sync.httprelay.protos.HttpRelayServerMessage)
    }

    static {
      defaultInstance = new HttpRelayServerMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:it.anyplace.sync.httprelay.protos.HttpRelayServerMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_it_anyplace_sync_httprelay_protos_HttpRelayPeerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_it_anyplace_sync_httprelay_protos_HttpRelayPeerMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_it_anyplace_sync_httprelay_protos_HttpRelayServerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_it_anyplace_sync_httprelay_protos_HttpRelayServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(src/main/resources/httpRelayProtos.pro" +
      "to\022!it.anyplace.sync.httprelay.protos\"\260\001" +
      "\n\024HttpRelayPeerMessage\022Q\n\014message_type\030\001" +
      " \001(\0162;.it.anyplace.sync.httprelay.protos" +
      ".HttpRelayPeerMessageType\022\022\n\nsession_id\030" +
      "\002 \001(\t\022\021\n\tdevice_id\030\003 \001(\t\022\020\n\010sequence\030\004 \001" +
      "(\003\022\014\n\004data\030\005 \001(\014\"\273\001\n\026HttpRelayServerMess" +
      "age\022S\n\014message_type\030\001 \001(\0162=.it.anyplace." +
      "sync.httprelay.protos.HttpRelayServerMes" +
      "sageType\022\022\n\nsession_id\030\002 \001(\t\022\030\n\020is_serve",
      "r_socket\030\003 \001(\010\022\020\n\010sequence\030\004 \001(\003\022\014\n\004data" +
      "\030\005 \001(\014*_\n\030HttpRelayPeerMessageType\022\013\n\007CO" +
      "NNECT\020\000\022\021\n\rPEER_TO_RELAY\020\001\022\021\n\rWAIT_FOR_D" +
      "ATA\020\002\022\020\n\014PEER_CLOSING\020\003*u\n\032HttpRelayServ" +
      "erMessageType\022\022\n\016PEER_CONNECTED\020\000\022\021\n\rDAT" +
      "A_ACCEPTED\020\001\022\021\n\rRELAY_TO_PEER\020\002\022\022\n\016SERVE" +
      "R_CLOSING\020\003\022\t\n\005ERROR\020\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_it_anyplace_sync_httprelay_protos_HttpRelayPeerMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_it_anyplace_sync_httprelay_protos_HttpRelayPeerMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_it_anyplace_sync_httprelay_protos_HttpRelayPeerMessage_descriptor,
              new java.lang.String[] { "MessageType", "SessionId", "DeviceId", "Sequence", "Data", });
          internal_static_it_anyplace_sync_httprelay_protos_HttpRelayServerMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_it_anyplace_sync_httprelay_protos_HttpRelayServerMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_it_anyplace_sync_httprelay_protos_HttpRelayServerMessage_descriptor,
              new java.lang.String[] { "MessageType", "SessionId", "IsServerSocket", "Sequence", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
